// JSON -> Lua source serializer
// Output is a Lua table literal that can be `require`d directly.
(function (global) {
  'use strict';

  function isInt(n) { return typeof n === 'number' && Number.isFinite(n) && Math.floor(n) === n; }
  function isIdent(k) { return typeof k === 'string' && /^[A-Za-z_][A-Za-z0-9_]*$/.test(k); }

  function isPureArray(v) {
    if (!Array.isArray(v)) return false;
    return true;
  }

  function isShortArray(v) {
    // Inline arrays of numbers (anchor, attachAt, color)
    if (!Array.isArray(v)) return false;
    if (v.length > 4) return false;
    return v.every(x => typeof x === 'number');
  }

  function fmtNum(n) {
    if (isInt(n)) return String(n);
    // strip trailing zeros, max 4 decimals
    return parseFloat(n.toFixed(4)).toString();
  }

  function escStr(s) {
    return '"' + String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
  }

  function dump(v, indent) {
    indent = indent || 0;
    const pad  = '    '.repeat(indent);
    const pad2 = '    '.repeat(indent + 1);

    if (v === null || v === undefined) return 'nil';
    if (typeof v === 'boolean') return v ? 'true' : 'false';
    if (typeof v === 'number')  return fmtNum(v);
    if (typeof v === 'string')  return escStr(v);

    if (isShortArray(v)) {
      return '{ ' + v.map(fmtNum).join(', ') + ' }';
    }

    if (Array.isArray(v)) {
      if (v.length === 0) return '{}';
      const parts = v.map(x => pad2 + dump(x, indent + 1));
      return '{\n' + parts.join(',\n') + ',\n' + pad + '}';
    }

    if (typeof v === 'object') {
      const keys = Object.keys(v);
      if (keys.length === 0) return '{}';
      // Inline very short objects (e.g. keyframe {t=0.1, rot=-90})
      const allSimple = keys.every(k => isIdent(k) && (typeof v[k] === 'number' || typeof v[k] === 'boolean' || v[k] === null));
      if (allSimple && keys.length <= 4) {
        const inline = keys.map(k => k + ' = ' + dump(v[k], 0)).join(', ');
        if (inline.length <= 80) return '{ ' + inline + ' }';
      }
      const parts = keys.map(k => {
        const key = isIdent(k) ? k : '[' + escStr(k) + ']';
        return pad2 + key + ' = ' + dump(v[k], indent + 1);
      });
      return '{\n' + parts.join(',\n') + ',\n' + pad + '}';
    }

    return 'nil';
  }

  function exportSkeletonLua(skeletonJson) {
    return '-- Auto-generated by skeleton2d editor. Do not edit by hand.\n'
         + 'return ' + dump(skeletonJson, 0) + '\n';
  }

  function exportAnimationsLua(animsJson) {
    return '-- Auto-generated by skeleton2d editor. Do not edit by hand.\n'
         + 'return ' + dump(animsJson, 0) + '\n';
  }

  global.LuaExport = {
    skeleton: exportSkeletonLua,
    animations: exportAnimationsLua,
    dump,
  };
})(window);
